packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - esbuild
  - sharp

catalog:
  typescript: 5.8.2
  next: ^16
  react: ^19
  react-dom: ^19
  oxlint: ^1.50.0
  oxlint-tsgolint: ^0.15.0
  oxfmt: ^0.35.0
