packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - esbuild
  - sharp

catalog:
  typescript: 5.8.2
  next: 15.2.3
  eslint-config-next: 15.2.3
  react: ^19
  react-dom: ^19
  eslint: ^8.57.0