blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/TheEdoRan/next-safe-action/discussions/new?category=ideas
    about: Do you want to help us improve the library? Open a new discussion to suggest an idea.
  - name: Ask a question
    url: https://github.com/TheEdoRan/next-safe-action/discussions/new?category=q-a
    about: Do you want to ask something about the library? Open a new discussion to get help from the community.